### ISSUE TITLE
Add new microchain agent new capabilities

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#135]
- sign up to farcaster + make posts of summarized learnings (see AutoTx)
- trading on cowswap + FX

**Comment by gabrielfior** [comment]
https://github.com/a16z/farcaster-py

**Comment by kongzii** [comment]
> trading on cowswap + FX

Are we already doing this?

**Comment by evangriffiths** [comment]
No, I guess this issue should have been split into 2. I've made a new one here for the second part: https://github.com/gnosis/prediction-market-agent/issues/163
