### ISSUE TITLE
Add ability of ThinkThoroughlyAgent to gather market predictions from existing correlated markets

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#138]
As a cost-saving(?) (so it doesn't have to do as much research itself) or performance enhancing (so it can get predictions for more sub-questions for the ~same cost) feature

**Comment by gabrielfior** [comment]
Note that simple prompts won't do the trick

![image](https://github.com/gnosis/prediction-market-agent/assets/4126235/71628fd1-e56a-44c9-ac07-299fdbd593e3)

**Comment by gabrielfior** [comment]
As validated with @evangriffiths :

The agent can have a function that:
- takes the market title as input
- create a local vector DB (e.g. Chroma)
- get a list of other open markets, gets their titles, embeds them, then adds these to the db. (add some clever logic here, e.g. check if embeddings of market already present, if not create embeddings)
- passes in the market title to a cosine similarity query to retrieve the similar markets
