### ISSUE TITLE
Add thumbnail generator for markets

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#139]
There is Streamlit demo for image generation: https://github.com/gnosis/prediction-market-agent/blob/main/scripts/image_app.py

But before using it, it's worth trying Midjourney as well.

Image generation should be relatively easy to implement, but storing it is a bit harder.

We need to deploy a new contract that will store the mapping between the market's address and uploaded image is hash.

**Comment by gabrielfior** [comment]
Regarding smart contract functionalities, I would suggest
-> Create a new project using foundry (https://github.com/foundry-rs/foundry) - we use parts of it for our local-chain testing
-> Create a new smart contract based on https://solidity-by-example.org/mapping/ + add a functionality to the `registerThumbnail` to only allow for market creator to register a thumbnail
-> Test compile, etc
-> Test deploying this locally
-> Test deploying this on Tenderly
-> Deploy on Gnosis testnet
-> Deploy on Gnosis mainnet

**Comment by kongzii** [comment]
Done in replicator, will continue in olas https://github.com/gnosis/prediction-market-agent/pull/262
