### ISSUE TITLE
Create Python functions from smart contract functions on-chain

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent#169]
Idea is to generate Python functions from Solidity functions in verified smart contracts.

-> Agent is pointed towards a smart contract, e.g. "Here is the smart contract of a DEX. The source code is here (address) - go take a look and understand what it is doing, maybe you can profit from it."
-> Agent can call this tool to generate a tool, which can then be used in the future for interacting with the smart contract.

**Comment by kongzii** [comment]
https://github.com/OpenDevin/OpenDevin could be useful here

**Comment by evangriffiths** [comment]
Gabriel says you can go from abi -> typescript already with https://viem.sh/
