### ISSUE TITLE
Add context to microchain agent app

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#171]
Make it more clear in the web UI that the agent 
- has a fixed wallet address 
- and you, the user are watching it transact

Add info somewhere:
- starting balance
- wallet address

**Comment by gabrielfior** [comment]
If you need more funds/want to test things out, we can have the agent run inside a "controlled" blockchain (see https://docs.tenderly.co/devnets/intro-to-devnets) which replicate the real chain and where we can fund wallets with lots of xDAI. So the agent has infinite money and can bet on all markets.

**Comment by evangriffiths** [comment]
Resolved with https://github.com/gnosis/prediction-market-agent/pull/189
