### ISSUE TITLE
Add ability for microchain agent to redeem winning bets

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#172]

**Comment by kongzii** [comment]
@evangriffiths I think this one is complete, is that right? https://github.com/gnosis/prediction-market-agent/blob/55177e6738b3c22192aef912ad15735c196ab8f1/prediction_market_agent/agents/microchain_agent/omen_functions.py#L23

**Comment by evangriffiths** [comment]
Ah nice, I forgot about that guy! Cheers
