### ISSUE TITLE
GPT-4o available in OpenAI's API

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#177]
The new and shiny GPT4o should be available in the API, they claim:

- 50% lower pricing. GPT-4o is 50% cheaper than GPT-4 Turbo, across both input tokens ($5 per 1 million tokens) and output tokens ($15 per 1 million tokens).
- 2x faster latency. GPT-4o is 2x faster than GPT-4 Turbo.
- 5x higher rate limits. Over the coming weeks, GPT-4o will ramp to 5x those of GPT-4 Turbo—up to 10 million tokens per minute for developers with high usage.

We should give it a try

**Comment by evangriffiths** [comment]
Done!
