### ISSUE TITLE
Microchain agent - (maybe) mech call needs rework

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent#217]
During testing of the microchain agent (`poetry run python <PATH>/microchain_agent.py`), following warning was logged:

```
>> PredictProbabilityForQuestionLocal(market_id="0x24e72c5784d38518ed40cd4b61e028fa3014f2f8")
ENGINE: gpt-4-0125-preview
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
0.95
>> Reasoning("The predicted probability of Android 15 being released for Pixel users by 29 May 2024 is 0.95, suggesting a very high likelihood that this event will occur. Given this high probability, it's crucial to check the current market probability to identify if there's an undervaluation in the market. If the market probability is significantly lower than 0.95, buying 'Yes' tokens could be a profitable move.")
The reasoning has been recorded
```

@evangriffiths probably a false alarm here, but could you please share more? Can this be safely ignored?

**Comment by evangriffiths** [comment]
Hmm I don't recognise that error. That is running the mechs locally (i.e. not using mech client). The only http requests will be openai calls and google search + webscrape calls. So maybe one of those failed? Is this reproducible or a one-off?

**Comment by gabrielfior** [comment]
It works now - closing this
