### ISSUE TITLE
Deploy microchain agent app in kube cluster

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#224]
The microchain agent currently has an interactive streamlit app deployed via streamlit https://autonomous-trader-agent.streamlit.app/

We can add auth features and scaling more easily if we deploy it to our kube cluster.

This streamlit app deploys a branch https://github.com/gnosis/prediction-market-agent/pull/179 that
- hardcodes the agent to use gpt3.5 (can be removed for kube deployment)
- contains the cloned mech repo (hack! 🙈) because streamlit can't deal with git submodules. This can be removed when the mech-client speed+reliability issues are fixed and we merge https://github.com/gnosis/prediction-market-agent/pull/124.

See https://gnosisinc.slack.com/archives/C06E4TU13E0/p1717064166525909 for context

See https://github.com/gnosis/prediction-market-agent/pull/179#issuecomment-2139156763 to deploy to kube once above merge issues are fixed.

**Comment by kongzii** [comment]
Done! https://autonomous-trader-agent.ai.gnosisdev.com
