### ISSUE TITLE
Write a blog post #1 + introduction post

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#231]

**Comment by gabrielfior** [comment]
It would be nice to have an image like this, for actions like 'buyTokens', 'sell', etc
![image](https://github.com/gnosis/prediction-market-agent/assets/4126235/942a8a35-2e8f-4404-aa06-e6c6b044a590)

**Comment by gabrielfior** [comment]
Draft being developed here -> https://www.notion.so/gnosischain/Blog-post-WIP-55e57e254edb405b8c555152e1b04c61?pvs=4

**Comment by gabrielfior** [comment]
Posts went live

https://www.gnosis.io/blog/introducing-the-general-agent
https://www.gnosis.io/blog/meet-gnosis-ai
