### ISSUE TITLE
Track deployed microchain agent on dune

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#232]
Address 0x220fFB0529ec8d5f84Dfbc5E4aBD9d1f0822f83a

**Comment by gabrielfior** [comment]
Available in the dashboard
https://dune.com/hdser/omen-ai-agents?agent_e64bd8=0x034c4ad84f7ac6638bf19300d5bbe7d9b981e736&agent_traders_eb0571=microchain-agent
