### ISSUE TITLE
Add ability for agent to create and monitor (sub-)goals

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#233]

**Comment by gabrielfior** [comment]
@evangriffiths can you please provide more context? Thx

**Comment by evangriffiths** [comment]
Is it possible with microchain? Yes:

- Add `SetGoal`/`GetGoals` functions?
- @kongzii says "we can just add them to system prompt

**Comment by gabrielfior** [comment]
Another option would be to manage this state in the DB, similar to what we do with prompts, but with a different session identifier. Something like

```
id(int) | session_identifier(str) | goal_identifier (str) | is_goal_done (bool)
1 | deployed-general-agent-omen | get-learnings | Done
1 | deployed-general-agent-omen | buy-yes | False
```
and we update the goals on the column `is_goal_done`
