### ISSUE TITLE
Microchain agent's balance is updated with a 1-iteration lag

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#241]
I think this is happening because 'get_balances' is run before the agent's execution.

**Comment by gabrielfior** [comment]
I would also observe that
-> function `get_balances` could store the result into `st.session_state.balance` (new variable)
-> after functions that alter the balance are called (e.g. `buyTokens`), we could call `get_balances` again - when this updates `st.session_state.balance`, the display is automatically re-rendered.
