### ISSUE TITLE
ThinkThoroughlyAgent's correlated markets feature has unexpected behaviour

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#263]
For the question `Will the LK-99 room temp, ambient pressure superconductivity pre-print replicate before 2025?` the correlated markets found all seemed unrelated:

<img width="906" alt="Screenshot 2024-06-21 at 11 50 38" src="https://github.com/gnosis/prediction-market-agent/assets/56087052/3930f250-d2a6-4e19-bb6a-9706de5be578">

Doesn't look like it's just a case of thresholds needing tweaking. For the question of `Will Joe Biden win the 2024 US Presidential Election?` there are obviously closely related markets, like `Will Biden be the democratic nominee?`, but instead the agent finds these markets:

<img width="891" alt="Screenshot 2024-06-21 at 12 02 52" src="https://github.com/gnosis/prediction-market-agent/assets/56087052/fc08713b-d909-430e-bdf9-19c0de17de34">

**Comment by gabrielfior** [comment]
That's important.
But for your argument of `Will Biden win`, Biden and Trump are to my knowledge not semantically related. So I guess any market that contains Trump in it's title will be closer to the market thus retrieved, right?

**Comment by kongzii** [comment]
> Biden and Trump are to my knowledge not semantically related

That's a question of how the embedding model is trained and what will be close in its embedding space. Often it's different from what a human would expect. Biden is a president, and Trump was, so it's possible they will be quite close.

**Comment by evangriffiths** [comment]
Also noting based on the 0%/100% probabilities that the correlated markets the agent is choosing appear to be closed. Would have thought we'd only want to pick open markets here.
