### ISSUE TITLE
Add 'tool call' stats section to deployed general agent viewer app

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#267]
I'm imagining a table/chart that summarizes the frequency of calls to each tool. For microchain this will involve parsing the agent's history.

**Comment by gabrielfior** [comment]
Can we retrieve the tool calls directly from the `engine.help` possibly? That would make this more organic.

**Comment by kongzii** [comment]
This would be cool also visualized on a timeline

**Comment by evangriffiths** [comment]
high priority because it's easy :)))))

**Comment by gabrielfior** [comment]
> Can we retrieve the tool calls directly from the `engine.help` possibly? That would make this more organic.

The above would involve storing the calls in the DB - since we have already the calls in the `memory` format, it's much easier to simply parse them from the DB and build a structure. So ignore the quoted comment and go for the original implementation that @evangriffiths suggested.
