### ISSUE TITLE
Deploy N general agents with learnable prompt

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#269]
Now that we have

1. Agent that can learn with randomness (sometimes the agent even completely fails and just loops through the learning functions, other times it's super fast to get into trading)
2. It can save/load its prompt from DB 
3. Viewer app

It would be interesting to have multiple instances of `just_born` agents and then watch and show to people how differently are they evolving their prompts and behaviour.

We'd need to:

1. Split `MICROCHAIN_AGENT_OMEN` in `AgentIdentifier` into multiple (e.g. `MICROCHAIN_AGENT_OMEN_0`, `MICROCHAIN_AGENT_OMEN_1`, etc)
2. Modify `DeployableMicrochainAgent` to allow select between them
3. Add their deployment
4. Modify the viewer app to switch between them

**Comment by evangriffiths** [comment]
why high?
- good for blog post (observe different behaviour, evidence of learning)
- good for debugging

**Comment by kongzii** [comment]
Will be closed by https://github.com/gnosis/prediction-market-agent/pull/305
