### ISSUE TITLE
Add `CallAPI` function to general agent

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#271]
Add a universal `CallAPI` function to a general agent, which will just use the `requests` library to make arbitrary calls. To any endpoint, with any parameters, etc.

**Comment by vishu1089** [comment]
on it!

**Comment by vishu1089** [comment]
Yes, I would love to!

**Comment by kongzii** [comment]
@vishu1089 Cool!

As an example, you can [take this action](https://github.com/gnosis/prediction-market-agent/blob/5304d2cb043072407627e5e5323436c45b74d052/prediction_market_agent/agents/microchain_agent/memory_functions.py#L13).

You can copy-paste and

1. Change the description accordingly
2. Change the example_args and __call__ function to accept `url` and `params` as input arguments
3. It should do a API call with requests library and return it's response (as string).

How exactly it will look like is open question, depends on what will work with LLM and the microchain framework.

For testing, you can[ add the new function here](https://github.com/gnosis/prediction-market-agent/blob/5304d2cb043072407627e5e5323436c45b74d052/prediction_market_agent/agents/microchain_agent/microchain_agent.py#L35) and then try to prompt the agent to use [it in the streamlit demo here.](https://github.com/gnosis/prediction-market-agent/blob/5304d2cb043072407627e5e5323436c45b74d052/prediction_market_agent/agents/microchain_agent/app.py).

Ping us if we can help along the way 🙏

**Comment by vishu1089** [comment]
Thanks, I'll check it out.

**Comment by vishu1089** [comment]
Got it, thanks!

**Comment by vishu1089** [comment]
Need some context, lemme know when can we connect?

**Comment by kongzii** [comment]
Closing as will be solved by https://github.com/gnosis/prediction-market-agent/pull/278
