### ISSUE TITLE
Use prediction prophet research report in ThinkThoroughly

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#302]
Right now, TT agent is doing it's own research https://github.com/gnosis/prediction-market-agent/blob/7e0d4534d83d9b16fe7d907e757483808329a825/prediction_market_agent/agents/think_thoroughly_agent/think_thoroughly_agent.py#L205.

It's doing better job in estimating probabilities between similar questions, yet it still underperforms in comparison with Prediction Prophet.

I thin what we could do is:

- Use prophet's logic in `generate_prediction_for_one_outcome`, [it can be cut out from here](https://github.com/gnosis/gnosis-labs-zuberlin2024/blob/main/trader/prediction.py#L15)
- Add prophet's report also to the `generate_final_decision` prompt

Because this is quite a huge change, I think instead of updating the current TT agent, there can be 2 of them living side by side and we can compare them later on.

**Comment by gabrielfior** [comment]
Agree with 2-agent approach (with shared components, e.g. scenario generation and correlated markets). Inheritance lends itself well I guess.

**Comment by kongzii** [comment]
Will be resolved by https://github.com/gnosis/prediction-market-agent/pull/315
