### ISSUE TITLE
Fix miss-report of prediction prophet errors in gcp logs

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#356]
Here in the code a multi-line string is logged https://github.com/agentcoinorg/predictionprophet/blob/0564033867cab3dd620239b042f9f294cb07fb4a/prediction_prophet/functions/research.py#L41

and it appears as errors in gcp:
![image](https://github.com/user-attachments/assets/c5019f5c-e999-4d08-aa78-83af94d4df3c)

https://console.cloud.google.com/logs/query;query=resource.labels.namespace_name%3D%22agents%22%0Aresource.labels.container_name%3D%22main%22%0Alabels.%22k8s-pod%2Fjob-name%22%3D~%22microchain-agent-omen-modif.*%22;cursorTimestamp=2024-08-01T01:35:25.403318644Z;resultsSearch=microchain;startTime=2024-07-30T06:22:47.847Z;endTime=2024-08-01T11:44:34.901Z?hl=en&project=gnosis-ai&pli=1

**Comment by evangriffiths** [comment]
Same here: https://github.com/agentcoinorg/predictionprophet/blob/0564033867cab3dd620239b042f9f294cb07fb4a/prediction_prophet/functions/research.py#L84

<img width="621" alt="Screenshot 2024-08-01 at 13 52 09" src="https://github.com/user-attachments/assets/e67de1ea-45ea-4295-9b89-96ee2cb35bd6">

**Comment by evangriffiths** [comment]
And here https://github.com/agentcoinorg/predictionprophet/blob/0564033867cab3dd620239b042f9f294cb07fb4a/prediction_prophet/functions/research.py#L94
<img width="936" alt="Screenshot 2024-08-01 at 13 53 28" src="https://github.com/user-attachments/assets/5fff1d43-136a-48d1-b62a-4ff9650c8797">

**Comment by kongzii** [comment]
Note that this has been originally fixed by https://github.com/gnosis/prediction-market-agent-tooling/blob/1e497fff9f2b53e4e3e1beb5dda08b4d49da881b/prediction_market_agent_tooling/loggers.py#L42, looks like something changed

**Comment by kongzii** [comment]
Closing with PR pending https://github.com/gnosis/prediction-market-agent/pull/364
