### ISSUE TITLE
Trader agent - if placing a contradicting bet into an existing user position, sell prev position

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent#423]
Agents are placing multiple bets in the same market (see `prediction_prophet_gpt4` and markets below) in ~ 10% of cases.
```
market 1 0x4d59a12a2ddff82436f185d8268b4caa559e51dc
market 2 0x78effa3e505c1c14f3cc0d8a4e255e5805014bc3
```
The accuracy on the 1st bet and 2nd bet are similar - hence it's not financially interesting to have contradicting bets, because one cancels the other and the payoff is negligible.
Instead, the agent should do one of 2 things:

1 - Don't place a bet in markets where the agent has already placed a bet
2 - Sell the previous position and open a new position in the new direction based on the agent's new prediction

**Comment by kongzii** [comment]
(2) makes most sense to me

> Sell the previous position

Not just the previous position but all of the previous positions in the other direction.

However, this will make measuring accuracy more complex. 

Maybe we shouldn't measure accuracy at all because it will get impossible anyway if the agent uses the Kelly strategy.

What about measuring only profitability on the agent level and accuracy on the market level?

**Comment by evangriffiths** [comment]
I prefer (2) as well.

> Maybe we shouldn't measure accuracy at all because it will get impossible anyway if the agent uses the Kelly strategy.

I guess no harm in measuring it, but agreed it loses its meaning once we change betting strategies. Then I think the only useable agent-level metric is ROI/profitability, as you say.

I think it's still important to measure prediction accuracy (or even better, mean-squared-error/Brier score) at the agent level. This becomes easier after @gabrielfior's [refactor](https://github.com/gnosis/prediction-market-agent-tooling/pull/352), but atm would still require some off-chain DB (either ipfs for mechs, or our own postgred db for our deployments).

**Comment by gabrielfior** [comment]
How to move forward with this
1. Let's go with (2) - sell previous positions, due to prev. votes
2. Accuracy will be accomplished here https://github.com/gnosis/prediction-market-agent-tooling/issues/363

**Comment by kongzii** [comment]
I think this is done as well from https://github.com/gnosis/prediction-market-agent-tooling/pull/374
