### ISSUE TITLE
Try out new mech-client release, and re-evaluate suitability for 'Marketplace of Tools'

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#431]
See release https://github.com/valory-xyz/mech-client/releases/tag/v0.2.16, which contains https://github.com/valory-xyz/mech-client/pull/49

Can we now create an agent that starts with no skills, and acquires them at run-time? (the dream 🙌 )

Once evaluated, update the nevermined/olas comparison: https://www.notion.so/gnosischain/Nevermined-vs-Olas-Mech-4bbe7f4f89cd4cbf9f6226b236127e8c

**Comment by gabrielfior** [comment]
> Can we now create an agent that starts with no skills, and acquires them at run-time? (the dream 🙌 )

We can start those, but currently all Olas-mechs (accessible via mech-client) are of the type `prompt -> response`, which we can also already accomplish directly via direct calls to OpenAI (no need to go through mech).
Once the more useful mechs (with more complex logic) become available via mech-client, check out this branch (https://github.com/gnosis/prediction-market-agent/commits/gabriel/olas-marketplace-using-io-schema/) and continue the work. Until then, this doesn't have high priority (so marking this as won't do, until other mech tools (e.g. buyTokens on Omen) become available).
