### ISSUE TITLE
Decide if we should change how to select markets to bet on

### ISSUE THREAD

**Issue by evangriffiths** [gnosis/prediction-market-agent#444]
atm `DeployableTraderAgent` by default gets markets closing soonest, sorted by ascending close time, and bets on the 0th one of these (if various conditions are met).

This means agents will likely only bet on each market once, and therefore the market p_yes won't move over time in the way it does on polymarket/manifold

Note this is really a PMAT issue, but the relevant milestone is for PMA

**Comment by gabrielfior** [comment]
Some thoughts
-> What we want here is to `move the market`, i.e. place higher bets (hopefully correct) that realistically reflect the expectation related to market X.

How can we move the market?
- `KnownOutcomeAgent` can place bets as large as possible (mechanism on PMAT available for this) to drain every possible cent from the market. This should make the odds jump to 0 or 1 (converges odds), but there's still a gap between market creation and outcome reveal (after which KnownOutcomeAgent is able to operate).
- In order to move the market, we need to buy more `outcomeTokens`. This can be achieved via either a. more agents and/or b. larger bets. Simply increasing the number of agents betting on each market would help here.

Other interesting question: `"which market should I bet on next"?` In my opinion, we should bet on the one with highest Expected Value, i.e. `max(agent_estimate_p_yes - market.p_yes)`. This would mean scan all markets, create 1 prediction for each, sort by EV and place bets on N markets, following the Kelly criterion.
In the above, API costs can be a challenge, hence an alternative like Replicate or Ollama could be investigated.

@evangriffiths let me know if these unstructured comments should be converted into tickets 🙏

**Comment by kongzii** [comment]
I like this idea a lot. We need to take care while implementing it, but it could be a great agent.

A few things in mind:

- If we would introduce this to all the agents, some markets could be left out without any predictions. Which I can imagine isn't great, at least some probabilities on every market with reasonable liquidity would be nice.
- It could happen that the agent will select the same market in multiple subsequent runs. So maybe there should still be some `don't bet on the same market in the last 24 hours` logic?
- How we will track this in Langfuse? Currently agent is supposed to iterate over N markets, bet on all of them, and each is a separate trace in Langfuse.

**Comment by kongzii** [comment]
Related to this issue: Should (if yes then how) we bet on markets closing in months or years? For example [Will Gnosis Chain still use a stablecoin as a gas token by 12.12.2025?](https://presagio.pages.dev/markets?id=0x27CBc733A5120371eDee84f77311b1e8659f6b51) it an interesting example that people asked for on Discord, but there are no bets from agents and won't be anytime soon with the current picking strategy.

I don't think these markets are interesting from profit point of view, they will drain N xDai that could be used on closing-soon markets and we won't see any profit from them for a long time.

However, I think we should bet on them at least a little. From PM-platform point of view, it's good to give people some prediction for their markets. But in the future, I'd probably create these long-running markets in sDai?

**Comment by kongzii** [comment]
> How we will track this in Langfuse? Currently agent is supposed to iterate over N markets, bet on all of them, and each is a separate trace in Langfuse.

Today, while annotating OFVChallenger's resolutions, I noticed that in OFVChallenger, all challenges are grouped under a single trace:

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/7ecce7d5-2ccc-4742-9c1e-1e07dd5450d9)

After annotation, it's still possible to treat them individually:

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/7a60ec2f-afd9-4b53-a3de-2e2a8db4e685)

So if we decide to predict all markets under a single trace, and then do some post-processing to select which one to bet on, or anything similar, it should be fine.

**Comment by gabrielfior** [comment]
Thanks for the previous comments. From those, I can split the discussion in 2:

1. Should we bet on markets even though betting there would yield suboptimal expected values? 
    -> I would say YES, simply because agents should also provide reasonable probabilities to those markets, where humans are unlikely to participate. We want to have predictions everywhere.
    -> Hence no ToDo here, agents continue to operate as they currently do.

2. Should we pick markets sorting by `max(expected_value)`?
    -> It seems like a good alternative to maximizing payouts for agents
    -> Conflicting bets (e.g. we bet both on YES and on NO, reducing the max payout) are avoided on PMAT in the current iteration https://github.com/gnosis/prediction-market-agent-tooling/pull/387
    -> Question now is: `how can we calculate expected_value of bets on a given market in a cost-efficient way`?

    **I would suggest the following (to be worked on a new ticket)**
    ->  Placing bets on markets closing soonest helps with accuracy (better forecasting). Let's say this selects 100 markets (configurable)
    -> We could use a cheaper model (e.g. gpt3.5) (without Tavily) so that we have a rough estimate for each market (100 forecasts) - consider using Replicate instead of OpenAI for costs
    -> Calculate `expected_value` for each market - this will differ from the actual expected value when placing the bet (since we use different models)
    -> Sort the markets. Let's say we pick the top 10.
    -> For the top 10, we run the "real" agent to answer all 10 markets. Finally, we sort all 10 by expected_value, and place a bet only on top 5 for example -> it's ok to place multiple bets on markets, since we use the previous bet as part of our `max_bet_amount`.

@evangriffiths @kongzii does the above make sense? If yes, happy to create tickets for these.

**Comment by kongzii** [comment]
> -> Hence no ToDo here, agents continue to operate as they currently do.

Not true, currently they aren't placing bets on long-running markets, eg. https://presagio.pages.dev/markets?id=0x27CBc733A5120371eDee84f77311b1e8659f6b51 is two weeks old without any bet

> We could use a cheaper model (e.g. gpt3.5) (without Tavily)

That doesn't make much sense to me. Doing predictions without an internet search with a model trained up to 2023 or something? They will be just (un)lucky guesses with high bias for easy questions.

Screenshotting my ideas from Slack:

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/1a1dc54d-86d1-49a0-bec1-9496fab93a64)

**Comment by evangriffiths** [comment]
Some other suggestions. If cost of predictions is a limiting factor (i.e. it's too expensive to bump prophetgpt4 to predict+bet on 100 markets), then we could either:
- just focus on a subset of markets, like the replicated markets (where we have 100% control) and bump the deployed agents to bet on more of these.
- develop a new agent that costs much less to bet, and have it bet on 100s of markets.
- ask for a beefier tavily subscription + a higher openai credit limit (the 'gnosis can do it' option)

> But in the future, I'd probably create these long-running markets in sDai?

Regardless of what we do to increase betting 'coverage', this disincentive to bet on long term markets will still be there, and this seems like the only solution. Is there any reason not to just make all markets with sdai collateral?

**Comment by kongzii** [comment]
> Is there any reason not to just make all markets with sdai collateral?

I was trying to find one, but didn't 😄 Atm all Replicated markets are in sDai: https://github.com/gnosis/prediction-market-agent/pull/465. 

Should we ask Olas to implement sDai as well?

**Comment by evangriffiths** [comment]
Ah nice!

> Should we ask Olas to implement sDai as well?

Good idea :)

**Comment by gabrielfior** [comment]
Writing down the notes after we discussed about this:		
-> Immediate ticket for increasing `bet_on_n_markets_per_run` to `MAX_AVAILABLE_MARKETS` (20) - https://github.com/gnosis/prediction-market-agent-tooling/issues/410
-> [Future ticket] Make `market_picking` decision modular - https://github.com/gnosis/prediction-market-agent-tooling/issues/411
-> [Future ticket] Track the correlation between `source_market` (on Polymarket or Manifold) with the market_odds seen on Omen for replicated markets. North star here is to have high correlation on all replicated markets (assuming high participation on the source market thus realistic odds). Ideally this would be tracked on Dune. - https://github.com/gnosis/prediction-market-agent-tooling/issues/412
