### ISSUE TITLE
Deploy FiveThirtyNine agent

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#470]
From Shorn on Slack:

> "On the 177 events, the Metaculus crowd got 87.0% accuracy, while FiveThirtyNine got 87.7% ± 1.4." (edited) 

Can we deploy it somehow? 

If they don't provide API, but if they are so good, perhaps it's worth going hacky and using [Selenium's](https://www.selenium.dev/) Python integration, to execute the prediction in "browser" with the agent?

**Comment by kongzii** [comment]
Did a quick look if it's even possible and unfortunately looks like it isn't. They have captcha on their website and it won't let you in programmatically with Selenium.

However, they do publish quite a lot of details about their system:

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/fb201bbf-a625-4f53-862d-6eb154186732)

So we could try to deploy a new agent based on their prompts.

**Comment by evangriffiths** [comment]
Duplicate of https://github.com/gnosis/prediction-market-agent/issues/460

The top-level code is here https://github.com/centerforaisafety/forecasting/blob/main/backend/src/fast_api.py :)

**Comment by kongzii** [comment]
Closing as duplicate
