### ISSUE TITLE
Selling outcomes

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#49]
Right now, our agents are only buying outcome tokens and then waiting for the resolution.

However, another potential profit is by:

1. We predict that p_yes probability is 70%
2. But the market's current p_yes is 40%
3. So we buy YES tokens
4. We look again into the market after some time, and if p_yes is >40, we can sell our YES tokens (we can either wait until it really hits our 70% prediction, or we can just sell for any reasonable profit)

Of course, the same logic applies to NO tokens.

Another selling point is if we changed our prediction, ie before it was 70% so we bought YES tokens, but now is 40%. Right now we would buy NO tokens and we would hold both YES and NO positions. But instead of that, we can sell the older YES tokens to minimise the loss.

**Comment by evangriffiths** [comment]
Done!
