### ISSUE TITLE
Replicator should also bond 10 xDai on Reality and challenge previous answers if bond is low

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#500]
Initially, I thought that Replicator doesn't have to bond 10 xDai because it's just copy-pasting correct answers.

However, it happens that these markets aren't answered by replicator, for example [1](https://reality.eth.limo/app/#!/network/100/question/0x79e32ae03fb27b07c89c0c568f80287c01ca2e57-0x8c487b25bbf202e5789929e904c80e6d825092f154f37e5e9acf8189e28363d5/token/XDAI) [2](https://reality.eth.limo/app/#!/network/100/question/0x79e32ae03fb27b07c89c0c568f80287c01ca2e57-0x538476593b8bad5bfd5d37ea7d0029b903db2a84ad9b1f1fc99bfe16d57a7197/token/XDAI) (I'm not saying these are wrong resolutions, just that they don't come from Replicator). Or they could be cheaply over-turn by anyone in their favor.

I now think that similarly as Challenger, Replicator should also bond 10 xDai and always submit an answer if the previous bond is < 5 xDai.

**Comment by evangriffiths** [comment]
> I'm not saying these are wrong resolution, just that they don't come from Replicator

Where is the answer coming from, if not the replicator? Just some random person is beating replicator to it?

**Comment by evangriffiths** [comment]
Also, I can't remember the rule for if the bonded answer is the same as what the replicator thinks. Is there any point in the replicator answering in the case where it agrees (and might it even lose money)?

**Comment by kongzii** [comment]
From one of the betters. The "free money motivation" is indeed motivating: 

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/0b173e1f-2211-455c-aad0-f76fece7c7a5)

**Comment by kongzii** [comment]
> Also, I can't remember the rule for if the bonded answer is the same as what the replicator thinks. Is there any point in the replicator answering in the case where it agrees (and might it even lose money)?

Hmm, maybe it's really not necessary in this case.

If you are answering with the same answer, you have to pay to the previous answerer his bond.

Which is desirable on Challenger, to motivate people to fix the answer. But here if they agree with the Replicator answer, there is maybe no need to increase bond? As the answer is copy pasted from other platform and so it should be correct?

No strong preference on my side on this 🤔

**Comment by gabrielfior** [comment]
> Also, I can't remember the rule for if the bonded answer is the same as what the replicator thinks. Is there any point in the replicator answering in the case where it agrees (and might it even lose money)?

I also can't remember - can we document this somewhere? I found [this](https://realitio.github.io/docs/html/fees.html) but not 100% clear to me.

**Comment by kongzii** [comment]
> I also can't remember - can we document this somewhere? I found [this](https://realitio.github.io/docs/html/fees.html) but not 100% clear to me.

I don't think I can write it better than they did 😄 But feel free to write it somewhere down

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/b54a1728-1dd1-4b0d-a20c-b0e8914c3c45)

**Comment by evangriffiths** [comment]
> If you are answering with the same answer, you have to pay to the previous answerer his bond.

Okay. So it seems like if it agrees, no need to also answer, otherwise challenge (unless, as you say, the bond is >5 xDai)

**Comment by kongzii** [comment]
Will be closed by https://github.com/gnosis/prediction-market-agent/pull/503
