### ISSUE TITLE
Create "Invalid agent"

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#505]
The agent would use the upcoming `is_invalid` method from PMAT. If the market is deemed invalid, the agent will buy the cheaper outcome tokens (without any further prediction).

Buying the cheaper outcome tokens on invalid markets will yield profit, because after it's resolved as Invalid, outcome tokens are worth equally.

**Comment by evangriffiths** [comment]
> after it's resolved as Invalid, outcome tokens are worth equally.

Seriously?! I assumed that if a market is resolved invalid that everyone just gets their money back (though not sure how that would work in practice, thinking about it 😅)

**Comment by kongzii** [comment]
>  after it's resolved as Invalid, outcome tokens are worth equally.

> Seriously?! I assumed that if a market is resolved invalid that everyone just gets their money back (though not sure how that would work in practice, thinking about it 😅)

Yeah 😄 See https://github.com/gnosis/realitio-gnosis-proxy/blob/64e70b9248413a5ed2af5269b816f14bd4cd1db0/contracts/RealitioProxy.sol#L49

**Comment by kongzii** [comment]
Tested that this will work here https://github.com/gnosis/prediction-market-agent-tooling/pull/517 (assuming that it will detect invalid markets correctly of course)

**Comment by kongzii** [comment]
Will be done by https://github.com/gnosis/prediction-market-agent/pull/527/files
