### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#571]
TODO: Write down how/where we are going to store prompts and messages.

**Comment by kongzii** [comment]
Discussed on sync: Let's use Postgres, but in a way that makes it easily switchable to something else if we want to in the future.

**Comment by kongzii** [comment]
It seems like our `LongTermMemoryTableHandler` from the microchain agent is doing just what we need --> saving all the actions that the agent is doing, and then we can query it in the web app.

And we also have `PromptTableHandler` from the agent that is capable of updating its system prompt.

**Comment by gabrielfior** [comment]
> So no actions needed for now in this issue.

So the ticket can be closed, right?

**Comment by kongzii** [comment]
Yep looks like it!
