### ISSUE TITLE
Receiving messages

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#572]
1. **Purely blockchain based (Gabriel’s favorite)**
    1. User wants to interact with `agent 1`
    2. User sends 0.1 xDAI to agent 1’s wallet and, in the data field, sends a hex-string (with the ~~base64~~zlib-encoded `prompt`)
    3. Agent 1 keeps track of new transactions, processes them sequentially

We need a function to read these messages and save somewhere what it already read, based on https://github.com/gnosis/prediction-market-agent/issues/571

However, reading needs to be a bit clever, not just reading and interacting with everything:

> Sounds good. I’m thinking how we enforce they send some reasonable xDai.
> Perhaps it can be prompted in the agent itself? Like
> `Don’t read any messages under N xDai. If there are multiple un-read messages, read the one with highest xDai value.`
> That way, it’s easy to implement, and the message cost could serve as transaction cost on blockchains. If someone is cheap, his message will be read as last, if at all 😅

Update: To make the implementation simpler for now, we will have just a fixed minimal fee amount for now.

**Comment by gabrielfior** [comment]
Closed by #579
