### ISSUE TITLE
Prepare agents' wallets, NFT and Safe

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#577]
- Deploy one NFT
- Mint 5 new NFT tokens
- Create 5 new addresses
    - Assign 1 address per agent
    - Transfer 0.2 xDAI per agent (for completing transactions later)
    - Transfer 1 NFT to each agent
    - Create a Mech for each NFT
- Create a new Safe
- Add 10 xDAI to the Safe (for testing purposes)
- Add each Mech as signer to Safe

**Comment by gabrielfior** [comment]
Added to password manager
