### ISSUE TITLE
Responding to messages from people

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#580]
In this case, I guess we can just "print the message" in the streamlit app. And perhaps highlight it somehow so people don't miss it.

**Comment by gabrielfior** [comment]
Assuming Freysa serves as blueprint, I believe "printing in the app" is good enough - we should just store them somewhere (as described https://github.com/gnosis/prediction-market-agent/issues/571) in order to justify who got the NFT and how.

**Comment by kongzii** [comment]
Implemented the function in https://github.com/gnosis/prediction-market-agent/pull/581, rest needs to be finished in

- https://github.com/gnosis/prediction-market-agent/issues/570 --> highlighting these messages
- https://github.com/gnosis/prediction-market-agent/issues/571 --> storing messages
