### ISSUE TITLE
Use DBManager at remaining places

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#586]
Instead of using `create_engine` manually

**Comment by gabrielfior** [comment]
I could only find 1 usage

https://github.com/gnosis/prediction-market-agent/blob/7debcc3c8fc30c64c885676132aa9c76eb3e8023/prediction_market_agent/db/sql_handler.py#L16

Anything else?

**Comment by kongzii** [comment]
Nope, nothing comes to mind. APIs are also create_engine-free https://github.com/search?q=repo%3Agnosis%2Flabs-api%20create_engine&type=code
