### ISSUE TITLE
Compare performance of agent using Return on Investment (ROI)

### ISSUE THREAD

**Issue by gabrielfior** [gnosis/prediction-market-agent#78]
Currently, we track our agent's precision (see Dune dashboard) as main metric. Another interesting metric is the Return on Investment (ROI) of the agent, i.e. what is the financial performance of the agent vs time.

One way to do this would be to track the agent's funds across multiple "assets", for example:

-> Agent starts with initial funding of 10 xDAI (block 0, balance is 10 xDAI == 10 USD)
-> Agent places bet on Omen market A and buys 10 YES tokens (assume price of 1 yes token is 0.99 USD) on block 1
    -> Balance on block 1 is 10 yes tokens * price_in_usd = 10 * 0.99 = 9.90 USD
-> On block 2, YES token accrued value and is now worth 1.01 USD - on block 2, agent's balance is 1.01 * 10 = 10.10 USD

The rationale above can be expanded for multiple markets on Omen.

One way to implement this involves
-> Fetching all markets where agent has placed bets
-> For each market:
    -> Fetch agent's balance of each outcome token (with historical block since we want to track this vs time)
    -> For each balance:
        -> Fetch price of outcome token, multiply that with balance

We should also investigate how to add this data to the Dune's dashboard.

**Comment by evangriffiths** [comment]
Added to Dune dashboard
