### ISSUE TITLE
Think Thoroughly agent improvements

### ISSUE THREAD

**Issue by kongzii** [gnosis/prediction-market-agent#88]
This agent was implemented based on https://github.com/gnosis/prediction-market-agent/issues/40.

The main idea was to create many subquestions based on the main one:

```
I think similar techniches as the evo researcher (multi-agent approach) can be used.
There can be a "prediction manager" that asks related question:
Overall input:
How likely to reach 100k user in 2024; and a research report
Process:
Create subquestions:
How likely to reach 10k user, 50k user, 100k, 200k by 2024
How likely to reach those number by mid 2024 or by end of 2025
How likely to not et least reach ...
And than basically give a probability to each of those and then make sure they are all coherent.
```

and then some ideas on top of it:

```
Annotate text with: from what date is it
Chain of events
How many days left till resolution?
How would a different resolution date influence the prediction?
-What are necessary conditions for the event to be true?
What is the likelihood of those conditions?
What is the prediction for the opposite event? (does that match with the initial prediction)
```

Using the new streamlit demo from https://github.com/gnosis/prediction-market-agent/pull/85/files, we can play with the agent easily and here are some insights with possible improvements:

**Comment by kongzii** [comment]
Question: Will GNO hit $500 before end of 2024?

Generated subquestions:
- GNO will not hit 500 before the end of 2024
- GNO will hit 500 or more before the end of 2024

Result: 20% on yes

Here it generates two subquestions, but we could have much more of them (will it hit 200? 300? 800? will it do it by 2025? 2030?)

If we ask the opposite question: Will GNO be below $500 before end of 2024?
Subquestions: Against 2, similarly as before.

Result: 30% on yes

The result should be pretty mach the opposite (80%), but isn't for some reason.

If we go more into the future: Will GNO hit $500 before end of 2030?

Then result is 20% on yes, but it should be much higher then hitting it by the end of 2024.

---

So seems like the question generation isn't working so well, some prompting needed there.

**Comment by kongzii** [comment]
Currently deployed model uses gpt 3.5 turbo, if I switch to the newest gpt 4 turbo, the outcome probs are much better:

Will GNO hit $500 before the end of 2030? --> 65% on yes
Will GNO be below $500 before end of 2030? --> 35% on yes

Also the year change is better:

Will GNO hit $500 before the end of 2024? --> 15% on yes
Will GNO hit $500 before the end of 2050? --> 80% on yes

But it still generates only 2 subquestions.

**Comment by kongzii** [comment]
Seems like gpt 4 turbo is also provided with the current date, this looks nice:

Question: Will GNO today hit $500?
Result: 0.02%

Will GNO hit $400 today?
Result: 0.1% yes

Will GNO hit $335 today?
Result: 100% yes

**Comment by gabrielfior** [comment]
This is to me 99% a matter of improved prompt engineering.
For example, this is the prompt for generating outcomes (https://github.com/gnosis/prediction-market-agent/blob/main/prediction_market_agent/agents/think_thoroughly_agent/prompts.py#L1-L23), excerpt below

```
CREATE_OUTCOMES_FROM_SCENARIO_PROMPT = """
        You are asked about a SCENARIO, which can have multiple, mutually-exclusive outcomes.
        You should break down the SCENARIO into a list of possible outcomes.
        
        Example 1:
        - SCENARIO: Will Gnosis Pay reach 100,000 users by 2025?
        - Answer: '''
            - Gnosis Pay reaches less than 25,000 users by 2025
            - Gnosis Pay reaches more than 25,000 users but less than 50,000 users by 2025
            - Gnosis Pay reaches more than 50,000 users but less than 75,000 users by 2025
            - Gnosis Pay reaches 100,000 users or more by 2025
        '''

        Example 2:
        - SCENARIO: Will the price of Bitcoin go up again in the next 2 months?
        - Answer: '''
            - The price of crypto will go up in the next 2 months
            - The price of crypto will not go up in the next 2 months
        '''
        
        [SCENARIO]
        {scenario}
        """
```

Hence by playing around with those prompts, one can get further breakdowns.
Additionally, I suggested waiting on the Langfuse integration (#79 and #80 ) to get further insights.

**Comment by kongzii** [comment]
> waiting on the Langfuse integration 

How will langchain help? In streamlit, we can see everything necessary.

**Comment by kongzii** [comment]
It will be closed by https://github.com/gnosis/prediction-market-agent/pull/104, but there can always be yet another iteration on this agent. Many possible improvements
